### PR TITLE
Added batch mode option

### PR DESCRIPTION
**Pull request by bram-pkg**
When `batch.mode=true` is set as a System Property then logging is disabled for the progress listener.

### CODE REVIEW

**Review by ihorman — APPROVED** [review]

**Review by MuJIuCTaH — CHANGES_REQUESTED** [review]
Hi  BramCeulemans,

I could not approve this pull request:
- Compilation error for variable [multipartEntity](https://github.com/jelastic/jelastic-maven-plugin/blob/a5fcce8a6fa29da10bcff1e225049950710fe9f1/src/main/java/com/jelastic/JelasticMojo.java#L690) that declared inside if conditional and used outside of this
- Separate constant for key batch.mode

**Comment by bram-pkg** [comment]
Fixed the compile error and added a global constant for `batch.mode`. @MuJIuCTaH

**Comment by BramCeulemans** [comment]
@MuJIuCTaH this is fixed!

**Comment by BramCeulemans** [comment]
Bump

**Comment by bram-pkg** [comment]
Guys?

**Comment by MuJIuCTaH** [comment]
Hi Bram,
First of all sorry for the late reply,
Our QA department check changes  and I'll accept your pull request.

**Comment by MuJIuCTaH** [comment]
Hi Bram,

Our QA has checked changes. As a conclusion, option batch.mode isn't working. It is always false.

The reason is that method [https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#getBoolean(java.lang.String)](url)
does not parse boolean primitive, it gets it from environment variables and then parses it.

So in following code:
 `final boolean batchMode = Boolean.getBoolean(System.getProperty(BATCH_MODE, "false"));`
you are trying to get environment variable with name true or false.

I have one more question:
In what cases do you use this option?

**Comment by bram-pkg** [comment]
It does work work when you add the batch.mode option to the JVM. We are using Jelastic in our company and want to disable the percentage logging for the uploading.

**Pull request closed without merging**
